In [2]:
"""Organise and filter relevant data from datasets to collect important info."""

# Import libraries
import pandas as pd

In [3]:
# Set relevant dataset
TEST_2020 = 'datasets/2020_01.csv'
# Code number used for NO2
POLLUTANT_CODE = 8

In [4]:
def load_csv_file_as_data_f(path: str) -> pd.DataFrame:
    """Load CSV file.

    Args:
        path (str): Path to file

    Returns:
        pd.DataFrame: Pandas Dataframe.

    """
    return pd.read_csv(path, sep=',')

In [5]:
original_csv = load_csv_file_as_data_f(TEST_2020)
original_csv

,CODI_PROVINCIA,PROVINCIA,CODI_MUNICIPI,MUNICIPI,ESTACIO,CODI_CONTAMINANT,ANY,MES,DIA,H01,...,H20,V20,H21,V21,H22,V22,H23,V23,H24,V24
0,8,Barcelona,19,Barcelona,4,7,2020,1,1,3.0,...,18.0,V,40.0,V,44.0,V,31.0,V,33.0,V
1,8,Barcelona,19,Barcelona,4,7,2020,1,2,13.0,...,18.0,V,10.0,V,3.0,V,57.0,V,NaN,N
2,8,Barcelona,19,Barcelona,4,7,2020,1,3,33.0,...,56.0,V,46.0,V,40.0,V,32.0,V,NaN,N
3,8,Barcelona,19,Barcelona,4,7,2020,1,4,12.0,...,5.0,V,7.0,V,2.0,V,3.0,V,NaN,N
4,8,Barcelona,19,Barcelona,4,7,2020,1,5,1.0,...,73.0,V,53.0,V,33.0,V,29.0,V,25.0,V
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1274,8,Barcelona,19,Barcelona,58,14,2020,1,27,60.0,...,60.0,V,58.0,V,60.0,V,61.0,V,NaN,N
1275,8,Barcelona,19,Barcelona,58,14,2020,1,28,58.0,...,62.0,V,58.0,V,61.0,V,65.0,V,NaN,N
1276,8,Barcelona,19,Barcelona,58,14,2020,1,29,70.0,...,24.0,V,42.0,V,49.0,V,50.0,V,51.0,V
1277,8,Barcelona,19,Barcelona,58,14,2020,1,30,36.0,...,46.0,V,56.0,V,61.0,V,60.0,V,56.0,V
1278,8,Barcelona,19,Barcelona,58,14,2020,1,31,55.0,...,75.0,V,63.0,V,68.0,V,60.0,V,NaN,N

In [ ]:
def filter_pollutant(orig_df: pd.DataFrame) -> pd.DataFrame:
    """Filter to only NO2 relevant stats.

    Args:
        orig_df (pd.DataFrame): The original CSV dataframe.

    Returns:
        pd.DataFrame: The data filtered to NO2.

    """
    return orig_df[orig_df['CODI_CONTAMINANT'] == POLLUTANT_CODE].copy()

In [7]:
filtered_csv = filter_pollutant(original_csv)
filtered_csv

,CODI_PROVINCIA,PROVINCIA,CODI_MUNICIPI,MUNICIPI,ESTACIO,CODI_CONTAMINANT,ANY,MES,DIA,H01,...,H20,V20,H21,V21,H22,V22,H23,V23,H24,V24
29,8,Barcelona,19,Barcelona,4,8,2020,1,1,27.0,...,64.0,V,66.0,V,63.0,V,56.0,V,48.0,V
30,8,Barcelona,19,Barcelona,4,8,2020,1,2,37.0,...,67.0,V,61.0,V,49.0,V,60.0,V,NaN,N
31,8,Barcelona,19,Barcelona,4,8,2020,1,3,53.0,...,43.0,V,40.0,V,39.0,V,38.0,V,NaN,N
32,8,Barcelona,19,Barcelona,4,8,2020,1,4,34.0,...,37.0,V,36.0,V,22.0,V,20.0,V,NaN,N
33,8,Barcelona,19,Barcelona,4,8,2020,1,5,13.0,...,73.0,V,69.0,V,61.0,V,54.0,V,49.0,V
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1187,8,Barcelona,19,Barcelona,58,8,2020,1,27,4.0,...,8.0,V,11.0,V,9.0,V,8.0,V,NaN,N
1188,8,Barcelona,19,Barcelona,58,8,2020,1,28,9.0,...,10.0,V,11.0,V,7.0,V,4.0,V,NaN,N
1189,8,Barcelona,19,Barcelona,58,8,2020,1,29,3.0,...,46.0,V,27.0,V,21.0,V,18.0,V,15.0,V
1190,8,Barcelona,19,Barcelona,58,8,2020,1,30,28.0,...,15.0,V,7.0,V,5.0,V,5.0,V,8.0,V
1191,8,Barcelona,19,Barcelona,58,8,2020,1,31,6.0,...,5.0,V,13.0,V,4.0,V,8.0,V,NaN,N

In [14]:
def calc_pollute_daily_avg(filtered_df: pd.DataFrame) -> pd.DataFrame:
    """Calculate average NO2 per day.

    Args:
        filtered_df (pd.DataFrame): Data frame with only relevant stations.

    Returns:
        pd.DataFrame: Dataframe with average NO2 values.

    """
    # Get the hour columns with values for NO2.
    hour_cols = [col for col in filtered_df.columns if col.startswith('H')]
    # Get the V cols which define whethere a value was gathered.
    valid_cols = [col for col in filtered_df.columns if col.startswith('V')]
    # Choose to drop any invalid values listed as "N" in the V column.
    for hour, value in zip(hour_cols, valid_cols, strict=False):
        filtered_df.loc[filtered_df[value] == 'N', hour] = None

    # Compute mean of valid hourly values
    filtered_df['no2_daily_avg'] = filtered_df[hour_cols].mean(axis=1)

    return filtered_df

In [15]:
calc_pollute_daily_avg(filtered_csv)

,CODI_PROVINCIA,PROVINCIA,CODI_MUNICIPI,MUNICIPI,ESTACIO,CODI_CONTAMINANT,ANY,MES,DIA,H01,...,V20,H21,V21,H22,V22,H23,V23,H24,V24,no2_daily_avg
29,8,Barcelona,19,Barcelona,4,8,2020,1,1,27.0,...,V,66.0,V,63.0,V,56.0,V,48.0,V,32.291667
30,8,Barcelona,19,Barcelona,4,8,2020,1,2,37.0,...,V,61.0,V,49.0,V,60.0,V,NaN,N,38.565217
31,8,Barcelona,19,Barcelona,4,8,2020,1,3,53.0,...,V,40.0,V,39.0,V,38.0,V,NaN,N,38.956522
32,8,Barcelona,19,Barcelona,4,8,2020,1,4,34.0,...,V,36.0,V,22.0,V,20.0,V,NaN,N,33.217391
33,8,Barcelona,19,Barcelona,4,8,2020,1,5,13.0,...,V,69.0,V,61.0,V,54.0,V,49.0,V,29.291667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1187,8,Barcelona,19,Barcelona,58,8,2020,1,27,4.0,...,V,11.0,V,9.0,V,8.0,V,NaN,N,8.000000
1188,8,Barcelona,19,Barcelona,58,8,2020,1,28,9.0,...,V,11.0,V,7.0,V,4.0,V,NaN,N,6.782609
1189,8,Barcelona,19,Barcelona,58,8,2020,1,29,3.0,...,V,27.0,V,21.0,V,18.0,V,15.0,V,19.130435
1190,8,Barcelona,19,Barcelona,58,8,2020,1,30,28.0,...,V,7.0,V,5.0,V,5.0,V,8.0,V,9.333333
1191,8,Barcelona,19,Barcelona,58,8,2020,1,31,6.0,...,V,13.0,V,4.0,V,8.0,V,NaN,N,6.652174